### ISSUE TITLE
[Week 2] 기본 과제

### ISSUE THREAD

**Issue by youz2me** [NOW-SOPT-iOS-Part/LeeYouJin-assignment#1]
## 📝 과제 내용
1️⃣ SnapKit을 사용해서 UI 구현하기
2️⃣ 아이디, 비밀번호 텍스트필드 각각 활성화되었을 때 border 컬러 수정하기
3️⃣ 아이디, 비밀번호 텍스트필드의 텍스트가 !isEmpty일 때 버튼 활성화하기
4️⃣ 활성화된 로그인하기 버튼을 클릭했을 때 아이디 데이터 전달하기
5️⃣ 비밀번호 텍스트필드 default 값에 security 적용하기
6️⃣ 눈 모양 버튼 클릭 시 security 해제하기
7️⃣ 글 삭제 버튼 클릭 시 아이디, 비밀번호 텍스트필드 각각 클리어하기

## ✔️ To-Do
- [ ] 1️⃣ SnapKit을 사용해서 UI 구현하기
- [ ] 2️⃣ 아이디, 비밀번호 텍스트필드 각각 활성화되었을 때 border 컬러 수정하기
- [ ] 3️⃣ 아이디, 비밀번호 텍스트필드의 텍스트가 !isEmpty일 때 버튼 활성화하기
- [ ] 4️⃣ 활성화된 로그인하기 버튼을 클릭했을 때 아이디 데이터 전달하기
- [ ] 5️⃣ 비밀번호 텍스트필드 default 값에 security 적용하기
- [ ] 6️⃣ 눈 모양 버튼 클릭 시 security 해제하기
- [ ] 7️⃣ 글 삭제 버튼 클릭 시 아이디, 비밀번호 텍스트필드 각각 클리어하기
