### ISSUE TITLE
🔥 Week 2: 도전 과제

### ISSUE THREAD

**Issue by youz2me** [NOW-SOPT-iOS-Part/LeeYouJin-assignment#3]
# 📝 과제 내용
1️⃣ BottomSheet 높이를 Screen의 50%로 제한하기
2️⃣ 아래에서 위로 올라오는 modal 형식으로 구현하기
3️⃣ 바텀시트에서 저장한 닉네임을 세번째 뷰에서 아이디 대신 보여주기
4️⃣ 닉네임 텍스트필드가 입력이 되었을 때, 버튼 활성화하기
5️⃣ 닉네임 텍스트필드의 텍스트는 한글로 제한하기

## ✔️ To-Do
- [ ] 1️⃣ BottomSheet 높이를 Screen의 50%로 제한하기
- [ ] 2️⃣ 아래에서 위로 올라오는 modal 형식으로 구현하기
- [ ] 3️⃣ 바텀시트에서 저장한 닉네임을 세번째 뷰에서 아이디 대신 보여주기
- [ ] 4️⃣ 닉네임 텍스트필드가 입력이 되었을 때, 버튼 활성화하기
- [ ] 5️⃣ 닉네임 텍스트필드의 텍스트는 한글로 제한하기

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
- 데이터의 흐름은 BottomSheet → 로그인 뷰 → 로그인 완료 뷰 순으로 진행하기
- 최대한 세미나에서 학습한 내용으로 구현하기
