### ISSUE TITLE
[Week Extra] MVVM 패턴 리팩토링 및 Observable Pattern 적용

### ISSUE THREAD

**Issue by youz2me** [NOW-SOPT-iOS-Part/LeeYouJin-assignment#9]
# 📝 과제 내용
- 기존 과제를 Observable Pattern을 적용해 MVVM 패턴으로 리팩토링합니다.

## ✔️ To-Do
- [x] Observable Pattern 패턴 공부
- [x] 기존 리팩토링 수정
- [x] Observable Pattern 패턴 적용
